<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sharepoint_connector"
 *
 * Auto generated by Extension Builder 2012-10-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Sharepoint Connector',
	'description' => 'Connector to sharepoint.',
	'category' => 'plugin',
	'author' => 'Erik Frister, Julian Kleinhans',
	'author_email' => 'erik.frister@aijko.de, julian.kleinhans@aijko.de',
	'author_company' => 'aijko GmbH, aijko GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.5',
			'fluid' => '1.5',
			'typo3' => '4.7',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>